name: "Terraform Plan on PR"

on:
  push:
    branches:
      - hcp

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write # Nécessaire pour l'authentification OIDC vers AWS
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Étape cruciale pour configurer l'authentification OIDC vers AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::850995556933:role/GitHubActions-Terraform-Role-Projet1 # Mettez l'ARN de votre rôle IAM
          aws-region: eu-west-3

      # Installation de Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Exécution de Terraform, avec le jeton pour le registre privé
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
